name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23lipVzLHX0gz9IGwR"
GITHUB_OWNER = "ffy168"
GITHUB_REPO = "NAS"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nas0-cr8.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://nas0-cr8.pages.dev"

